CREATE DATABASE IF NOT EXISTS hvacapp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hvacapp;

CREATE TABLE IF NOT EXISTS jobs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    job_date DATE NOT NULL,
    job_type VARCHAR(50) NOT NULL,
    customer_name VARCHAR(255) NOT NULL DEFAULT '',
    address_line1 VARCHAR(255) NOT NULL DEFAULT '',
    address_line2 VARCHAR(255) NOT NULL DEFAULT '',
    phone VARCHAR(30) NOT NULL DEFAULT '',
    system_type VARCHAR(50) DEFAULT NULL,
    job_data JSON DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_job_date (job_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
